// schemas.generated.ts
//
// AUTO-GENERATED by scripts/generate-openapi-schemas.ts. Do not edit by
// hand, edits will be overwritten on the next `npm run generate:schemas`.
// Source of truth is the actual TypeScript interfaces in services/.

export const generatedSchemas: Record<string, unknown> = {
  "FieldMatchResult": {
    "type": "object",
    "properties": {
      "match": {
        "type": "boolean"
      },
      "extracted": {
        "type": "string"
      },
      "applied": {
        "type": "string"
      },
      "needsReview": {
        "type": "boolean"
      }
    },
    "required": [
      "match",
      "extracted",
      "applied",
      "needsReview"
    ],
    "additionalProperties": false
  },
  "MatchResult": {
    "type": "object",
    "properties": {
      "overallMatch": {
        "type": "boolean"
      },
      "fields": {
        "type": "object",
        "additionalProperties": {
          "$ref": "#/components/schemas/FieldMatchResult"
        }
      }
    },
    "required": [
      "overallMatch",
      "fields"
    ],
    "additionalProperties": false
  },
  "ApplicationData": {
    "type": "object",
    "properties": {
      "brandName": {
        "type": "string"
      },
      "classType": {
        "type": "string"
      },
      "alcoholContent": {
        "type": "string"
      },
      "netContents": {
        "type": "string"
      },
      "producerName": {
        "type": "string"
      },
      "producerAddress": {
        "type": "string"
      },
      "countryOfOrigin": {
        "type": "string"
      }
    },
    "additionalProperties": {}
  },
  "BatchResultItem": {
    "type": "object",
    "properties": {
      "index": {
        "type": "number"
      },
      "ok": {
        "type": "boolean"
      },
      "result": {
        "$ref": "#/components/schemas/MatchResult"
      },
      "error": {
        "type": "string"
      }
    },
    "required": [
      "index",
      "ok"
    ],
    "additionalProperties": false
  },
  "ExtractedLabelFields": {
    "type": "object",
    "properties": {
      "brandName": {
        "type": "string",
        "nullable": true
      },
      "classType": {
        "type": "string",
        "nullable": true
      },
      "alcoholContent": {
        "type": "string",
        "nullable": true
      },
      "netContents": {
        "type": "string",
        "nullable": true
      },
      "producerName": {
        "type": "string",
        "nullable": true
      },
      "producerAddress": {
        "type": "string",
        "nullable": true
      },
      "countryOfOrigin": {
        "type": "string",
        "nullable": true
      },
      "warningStatement": {
        "type": "string",
        "nullable": true
      },
      "warningStatementFormatted": {
        "type": "object",
        "properties": {
          "governmentWarningAllCapsBold": {
            "type": "boolean"
          },
          "remainderIsBold": {
            "type": "boolean"
          }
        },
        "required": [
          "governmentWarningAllCapsBold",
          "remainderIsBold"
        ],
        "additionalProperties": false,
        "nullable": true
      }
    },
    "required": [
      "brandName",
      "classType",
      "alcoholContent",
      "netContents",
      "producerName",
      "producerAddress",
      "countryOfOrigin",
      "warningStatement",
      "warningStatementFormatted"
    ],
    "additionalProperties": false
  }
} as const;
